name: Test and Build

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip install -r requirements.txt
          pytest --cov --cov-fail-under=95 tests/ --cov-report=term-missing
      - name: Test and upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: .coverage

  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Install the required dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Requirements 
        run: |
          python -m pip install -r requirements.txt

      # Build the executable
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed main.py -n DodgeOrNot.exe

      - name: List dist folder
        run: ls dist || true

      # Bump the version and create a release
      - name: Bump version and create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/DodgeOrNot.exe
          name: DodgeOrNot.exe
          draft: false
          prerelease: false
          release_notes: |
            Automatic build and release of DodgeOrNot.exe
