name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Install the required dependencies
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pyinstaller
        run: |
          python -m pip install pyinstaller

      # Build the executable
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed main.py

      # Bump the version and create a release
      - name: Bump version and create release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.ref }}
          release_name: Release v${{ github.ref }}
          draft: false
          prerelease: false
          assets:
            - dist/main.exe